import '../models/operation.dart';
import '../models/player_state.dart';
import '../models/prestige_skill.dart';
import '../models/upgrade.dart';

/// Centralized deterministic game economy service.
/// All monetary and multiplier calculations must pass through this service.
class EconomyService {
  const EconomyService();

  /// Calculates the revenue generated by a single manual tap.
  double calculateTapIncome({
    required PlayerState playerState,
    required List<Operation> operations,
    required List<Upgrade> upgrades,
    required List<PrestigeSkill> prestigeSkills,
  }) {
    // Base tap value is 1.0 S-Coin + 1% of passive income/sec (scaling tap reward)
    final passiveIncome = calculateTotalIncomePerSec(
      operations: operations,
      upgrades: upgrades,
      prestigeSkills: prestigeSkills,
      trust: playerState.trust,
      prestigeMultiplier: playerState.prestigeMultiplier,
    );

    double tapBase = 1.0 + (passiveIncome * 0.01);

    // Apply global tap upgrades (targetOperationId == '')
    for (final upgrade in upgrades) {
      if (upgrade.isPurchased && upgrade.targetOperationId.isEmpty) {
        tapBase *= upgrade.multiplier;
      }
    }

    // Apply crypto syndicate tap bonus prestige skill
    for (final skill in prestigeSkills) {
      if (skill.id == 'skill_crypto_multiplier' && skill.level > 0) {
        tapBase *= (1.0 + skill.currentBonusValue);
      }
    }

    // Apply global prestige multiplier
    tapBase *= playerState.prestigeMultiplier;

    return tapBase;
  }

  /// Calculates Trust multiplier bonus (1.0 at 0% Trust, up to 1.5 at 100% Trust).
  double calculateTrustMultiplier(double trust) {
    final clampedTrust = trust.clamp(0.0, 100.0);
    return 1.0 + (clampedTrust / 100.0) * 0.5;
  }

  /// Calculates the effective income per second for a single operation.
  double calculateOperationIncomePerSec({
    required Operation operation,
    required List<Upgrade> upgrades,
    required List<PrestigeSkill> prestigeSkills,
    required double trust,
    double prestigeMultiplier = 1.0,
  }) {
    if (operation.level <= 0 || !operation.isUnlocked) {
      return 0.0;
    }

    double income = operation.currentIncomePerSecond;

    // Apply specific operation upgrades
    for (final upgrade in upgrades) {
      if (upgrade.isPurchased && upgrade.targetOperationId == operation.id) {
        income *= upgrade.multiplier;
      }
    }

    // Apply trust multiplier
    income *= calculateTrustMultiplier(trust);

    // Apply offshore laundering prestige skill bonus
    for (final skill in prestigeSkills) {
      if (skill.id == 'skill_offshore_laundering' && skill.level > 0) {
        income *= (1.0 + skill.currentBonusValue);
      }
    }

    // Apply global prestige multiplier
    income *= prestigeMultiplier;

    return income;
  }

  /// Calculates cumulative income per second across all active operations.
  double calculateTotalIncomePerSec({
    required List<Operation> operations,
    required List<Upgrade> upgrades,
    required List<PrestigeSkill> prestigeSkills,
    required double trust,
    double prestigeMultiplier = 1.0,
  }) {
    double total = 0.0;
    for (final op in operations) {
      total += calculateOperationIncomePerSec(
        operation: op,
        upgrades: upgrades,
        prestigeSkills: prestigeSkills,
        trust: trust,
        prestigeMultiplier: prestigeMultiplier,
      );
    }
    return total;
  }

  /// Calculates total heat generated per second across all active operations.
  double calculateTotalHeatPerSec({
    required List<Operation> operations,
    required List<PrestigeSkill> prestigeSkills,
  }) {
    double total = 0.0;
    for (final op in operations) {
      if (op.isUnlocked && op.level > 0) {
        total += op.currentHeatPerSecond;
      }
    }

    // Apply heat insulation prestige skill reduction
    for (final skill in prestigeSkills) {
      if (skill.id == 'skill_heat_insulation' && skill.level > 0) {
        total *= (1.0 - skill.currentBonusValue).clamp(0.1, 1.0);
      }
    }

    return total;
  }

  /// Calculates total trust generated per second across all active operations.
  double calculateTotalTrustPerSec({required List<Operation> operations}) {
    double total = 0.0;
    for (final op in operations) {
      if (op.isUnlocked && op.level > 0) {
        total += op.currentTrustPerSecond;
      }
    }
    return total;
  }

  /// Checks if player has sufficient funds to afford a cost.
  bool canAfford(double currentCoins, double cost) {
    return currentCoins >= cost && cost >= 0.0;
  }
}
